# Generated by Django 4.0.8 on 2023-01-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('is_special', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
                ('is_published', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.foodcategory')),
                ('toppings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.topping')),
            ],
            options={
                'db_table': 'Food',
            },
        ),
    ]
