# Generated by Django 4.0.8 on 2023-01-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='food',
            name='toppings',
            field=models.ForeignKey(db_column='toppings', on_delete=django.db.models.deletion.PROTECT, to='menu_app.topping'),
        ),
    ]
