# Generated by Django 4.0.8 on 2023-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_rename_is_published_food_is_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toppings',
        ),
        migrations.AddField(
            model_name='food',
            name='toppings',
            field=models.ManyToManyField(db_column='toppings', to='menu_app.topping'),
        ),
    ]
